# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5cde66c0f32e761b0c21eb4c74e57b7d8b6b65f5659febde7448492a2555c8beed3d97ef30353503b7044a1fc1991d7ed5290f17152b81b80dd00e460fd0c95

test:
  secret_key_base: 0af0e0ca3035dc218c760ad7d0dbfa1b48f1e2efc6a4d9dceb05c3504b94d51200d6fa2e60979c3288437f37d020e2b0ba57b0267f00f07888c676262af4d411

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
